# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/

executors:
  appnode:
    working_directory: ~/myapp
    docker:
      - image: circleci/node:latest

commands:
  restore_modules:
    steps:
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
  save_modules:
    steps:
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
jobs:
  build:
    executor: appnode
    steps:
      - checkout
      - restore_modules
      - run:
          name: install
          command: npm install
      - save_modules
  test:
    executor: appnode
    steps:
      - checkout
      - restore_modules
      - run:
          name: test
          command: npm run test
  deploy:
    executor: appnode
    steps:
      - checkout
      - restore_modules
      - run:
          name: deploy
          command: npm run deploy

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  main:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main

